### ISSUE TITLE
Gotags with CtrlPBufTag

### ISSUE THREAD

**Issue by bikbah** [jstemmer/gotags#19]
Can I use it with vim`s CtrPBufTag??

**Comment by adrianojn** [comment]
For CtrPBufTag you can use plain **ctags**.
on  `~/.ctags`:

	--langdef=Go
	--langmap=Go:.go
	--regex-Go=/func([ \t]+\([^)]+\))?[ \t]+([a-zA-Z0-9_]+)/\2/d,func/
	--regex-Go=/var[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/d,var/
	--regex-Go=/type[ \t]+([a-zA-Z_][a-zA-Z0-9_]+)/\1/d,type/

on `~/.vimrc`:

	let g:ctrlp_buftag_types = { 'go' : '--language-force=go --go-types=d' }

**Comment by bikbah** [comment]
@adrianojn, Thanx

**Comment by ches** [comment]
In case anyone wants to dig further into not needing to fall back to Exuberant Ctags for this, it appears to be because the `parseline` function [in buffertag.vim][1] expects to match a regular expression in the third field of the output, and gotags currently only has the line number there.

Either CtrlP could be improved to match either format, or gotags could have an option to output regexen?

[1]: https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp/buffertag.vim

**Comment by Perlence** [comment]
But `CtrlPTag` shows tags created by gotags, disregarding the third field is a line number. I guess `CtrlPBufTag` can be improved in that direction.
