### ISSUE TITLE
Make command interface compatible with Exuberant and Universal ctags

### ISSUE THREAD

**Issue by hsanson** [jstemmer/gotags#28]
Several editor plugins (e.g. vim-gutentags) invoke the tags generators with some specific flags:

>                                                 gutentags-ctags-requirements
> 
> If you're using the ctags modules (which is the default and only working one
> at this point, really), you will need a tags generator that supports the
> following arguments:
>
> * -f (to specify the output file)
> * --append (to append to an existing file while keeping it sorted)
> * --exclude (to exclude file patterns)
> * --options (to specify an options file)
>
> This means you probably want Exhuberant Ctags or Universal Ctags. The basic
> old BSD Ctags WON'T WORK. Other language-specific versions may or may not
> work. Check with their help or man page.

In order to be able to use gotags with these plugins it needs to accept at least these flags:

  - -f
  - --append
  - --exclude
  - --options

**Comment by hsanson** [comment]
Or even better add support for the xcmd protocol of Universal Ctags:

  https://github.com/universal-ctags/ctags/blob/master/docs/xcmd.rst

**Comment by dgsb** [comment]
@hsanson the xcmd link you provided seems broken. I could not either find references on this protocol in the universal ctags repository, could you provide some more information ?

**Comment by hsanson** [comment]
@dgsb seems that the feature was removed sometime this year....  so cannot be used anymore.

   https://github.com/universal-ctags/ctags/issues/1442

**Comment by thatnerdjosh** [comment]
Any tips on getting this to run with gutentags? Gutentags requires the `--append` flag... see https://github.com/ludovicchabant/vim-gutentags/issues/88#issuecomment-230371657

What I am seeing is it will overwrite all tags with each new file open, and will always only reflect the current file's tags

Not a good workaround but temporarily I just manually recursively generate them since it isn't a huge project
