### ISSUE TITLE
saving go files with tagbar opened, cursor will jump up and down

### ISSUE THREAD

**Issue by hellodudu** [jstemmer/gotags#43]
[https://github.com/majutsushi/tagbar/issues/486](https://github.com/majutsushi/tagbar/issues/486)

I'm facing this problem for a long time, and tagbar's team cann't reproduce this, they are not go developer and think it may be caused by go related plugins.

Would you please have a glance at gotags?

**Comment by alerque** [comment]
Hey — current tagbar maintainer here. Just dropping a note to say I'm happy to help facilitate a fix from the tagbar end of things if that is where the problem turns out to be, but I've never seen this anywhere on other languages and am not a Go developer so not really setup to test it locally. A MWE showing a Go source file and minimum rc arrangement of plugins even would give a place to start, but I do think it's going to turn out to be an issue with something in the Go toolchain people are using.

**Comment by jstemmer** [comment]
I'm not able to reproduce it locally with vim 8 and the latest versions of Tagbar and gotags (but without vim-go as I don't use it). It could be something specific to vim-go, maybe a combination of tools/scripts inside vim-go that are triggered when saving a file, a code formatter perhaps? A MWE would be helpful.

**Comment by hellodudu** [comment]
It works well when vim-go is disabled while gotags enabled, Most likely a problem with vim-go.
Sorry for bothering. Closing this issue.
